---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r}
load(file="kfz_data.Rdata")

res <- kcca(cluster_MM_scaled,k=10)

FeatureImp_kcca <- FeatureImpCluster(res,as.data.table(cluster_MM_scaled),sub = 1,biter = 10)
plot(FeatureImp_kcca,data=as.data.table(cluster_MM_scaled),color="type")

```


```{r}
### Artificial Cluster Dataset ####

### Random Dataset
set.seed(1234)
mat <- matrix(rnorm(4*10000),10000,4)
me<-2.5 # mean
x <- c(rnorm(5000,me,1),rnorm(5000,-me,1)) 
y <- c(rnorm(2500,me,1),rnorm(2500,-me,1),rnorm(2500,me,1),rnorm(2500,-me,1))
plot(x,y) # real clusters
data <- cbind(mat,x,y)
summary(data)
data<- scale(data)
summary(data)

# Original Group
org <- c(rep(1,2500),rep(2,2500),rep(3,2500),rep(4,2500))

# # Perform
# cl<- kmeans(data,4)
# # Compare clustering
# table(cl$cluster,org)


### Kmeans and feature imp ####

# flexclust
source("93 Relevant functions.R")
library(data.table)
library(ggplot2)
library(flexclust)

set.seed(7) # good clusters
set.seed(1234) # bad clusters
res <- kcca(data,k=4)
# table(res@cluster,org)

FeatureImp_res <- FeatureImpCluster(res,as.data.table(data),sub = 1,biter = 10)
plot(FeatureImp_res)


### Point count plot ####

# create data for plots
data2plot <- as.data.frame(data)
data2plot$cluster <- as.factor(res@cluster)
# stratifed samaple for plot
idx <- caret::createDataPartition(y=res@cluster,p=.1) # use ANOTHER package here
data2plot <- data2plot[idx$Resample1,]
#summary(data2plot$cluster)

ggplot(data2plot,aes(x=x,y=y,color=cluster)) + geom_point()
# Out of the box clustering did not work so well for the "bad" seed

# indeed, V3 is being used to assing obs to a cluster
# FeatureImp discovers this
ggplot(data2plot,aes(x=x,y=V3,color=cluster)) + geom_point()

# V3 and V4 do not seem to be relevant for the 


#### average over seed ####

set.seed(123)
nr_seeds <- 10
seeds_vec <- sample(1:1000,nr_seeds)

savedImp <- data.frame(matrix(0,nr_seeds,dim(data)[2]))
count <- 1
for (s in seeds_vec) {
  set.seed(s)
  res <- kcca(data,k=4)
  FeatureImp_res <- FeatureImpCluster(res,as.data.table(data),sub = 1,biter = 10)
  savedImp[count,] <- FeatureImp_res$featureImp[sort(names(FeatureImp_res$featureImp))]
  count <- count + 1
}
names(savedImp) <- sort(names(FeatureImp_res$featureImp))

sapply(savedImp,mean)
sapply(savedImp,median)

```

kmeans can be used via flexclust

```{r}
flexclust::as.kcca(cl, data=x) # cl is a kmeans object
flexclust::predict(cl2,newdata=x)
```



